<a href="https://colab.research.google.com/github/gtzan/csc349A_tzanetakis/blob/main/notebooks/linear_system_variations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

# Let's consider the following matrix representing a system of linear equations
# and solve of x (Ax = b)

A = [[1,3,5],
     [2,-3,2],
     [5, 5, -6]]
b = [12, 0, 20]

In [14]:
x = np.linalg.solve(A,b)
print(x)

[2.59296482 2.13065327 0.60301508]


In [19]:
# We can swap rows and the solution will not change - notice we have to swap rows
# for both A and b
A = [[2,-3,2],
      [1,3,5],
      [5, 5, -6]]
b = [0, 12, 20]
x = np.linalg.solve(A,b)
print(x)


[2.59296482 2.13065327 0.60301508]


In [20]:
# The first row is equal to zero - this means that we can can change
# the sign of all entries and still get the same result
# (if you think of it as an equation with variables this corresponds to moving
# all the variables to the opposite side)

A = [[-2,3,-2],
      [1,3,5],
      [5, 5, -6]]
b = [0, 12, 20]
x = np.linalg.solve(A,b)
print(x)

[2.59296482 2.13065327 0.60301508]


In [21]:
# For rows in which the b is not 0 we can do the same sign change but
# we have to match it with a change in the sign of the corresponding b value
# For example check the second row of both A and b in this case

A = [[-2,3,-2],
      [-1,-3,-5],
      [5, 5, -6]]
b = [0, -12, 20]
x = np.linalg.solve(A,b)
print(x)

[2.59296482 2.13065327 0.60301508]


In [22]:
# Finally note that reordering the columns solves the same system of linear equations but the order
# in which the solution values come out follows the same re-ordering i.e if
# the original system had variables (x,y,z) the reordered output (y,x,z)

A = [[3,-2,-2],
      [-3,-1,-5],
      [5, 5, -6]]
b = [0, -12, 20]
x = np.linalg.solve(A,b)
print(x)


[2.13065327 2.59296482 0.60301508]
